REFS_START_CHAR = "##"
REFS_START_CHAR_IN_TEXT = "##"
REFS_STOP_CHARS = ' ,];)'
FILE_EXTENSION = '.docx'

__ALL__ = [
    'REFS_START_CHAR',
    'STOP_CHARS',
    'REFS_START_CHAR_IN_TEXT',
    'FILE_EXTENSION',
]