REFS_START_CHAR = "##"
REFS_START_CHAR_IN_TEXT = "##"
REFS_STOP_CHARS = ' ,];)'
FILE_EXTENSION = '.docx'
PARAMETER_SAVED_MAIN_WINDOW_POZ = "Позиция и размер MainWindow"
TEXT_NO_INFORMATION = "- отсутствуют -"
TEXT_APPENDIX_FOR_NEW_FILE = " (new)"

BEFORE_NUM_PART_DEFAULT_VALUE = ""
BEFORE_NUM_PART_SAVE_NAME = "Символы перед номером"

AFTER_NUM_PART_DEFAULT_VALUE = "."
AFTER_NUM_PART_SAVE_NAME = "Символы после номера"

DEL_UNUSED_REFS_DEFAULT_VALUE = False
DEL_UNUSED_REFS_SAVE_NAME = "Удалить не использванную литературу из списка литературы в итоговом файле"

__ALL__ = [
    'REFS_START_CHAR',
    'STOP_CHARS',
    'REFS_START_CHAR_IN_TEXT',
    'FILE_EXTENSION',
    'PARAMETER_SAVED_MAIN_WINDOW_POZ',
    'TEXT_NO_INFORMATION',
    'TEXT_APPENDIX_FOR_NEW_FILE',
    'BEFORE_NUM_PART_DEFAULT_VALUE',
    'BEFORE_NUM_PART_SAVE_NAME',
    'AFTER_NUM_PART_DEFAULT_VALUE',
    'AFTER_NUM_PART_SAVE_NAME',
    'DEL_UNUSED_REFS_DEFAULT_VALUE',
    'DEL_UNUSED_REFS_SAVE_NAME',
]

Version = "1.002.20230425:21"
