# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt5Project/Windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(469, 528)
        MainWindow.setMinimumSize(QtCore.QSize(469, 528))
        MainWindow.setMaximumSize(QtCore.QSize(469, 528))
        MainWindow.setAcceptDrops(True)
        MainWindow.setWindowTitle("[ Замена ссылок в соответствии с их очерёдностью ]")
        MainWindow.setToolTip("")
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_src = QtWidgets.QLineEdit(self.centralwidget)
        self.file_src.setGeometry(QtCore.QRect(10, 30, 451, 21))
        self.file_src.setToolTip("")
        self.file_src.setStatusTip("")
        self.file_src.setWhatsThis("")
        self.file_src.setReadOnly(True)
        self.file_src.setObjectName("file_src")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 281, 16))
        self.label_2.setObjectName("label_2")
        self.file_dst = QtWidgets.QLineEdit(self.centralwidget)
        self.file_dst.setGeometry(QtCore.QRect(10, 80, 451, 21))
        self.file_dst.setToolTip("")
        self.file_dst.setStatusTip("")
        self.file_dst.setWhatsThis("")
        self.file_dst.setReadOnly(True)
        self.file_dst.setObjectName("file_dst")
        self.refs_found = QtWidgets.QTextBrowser(self.centralwidget)
        self.refs_found.setGeometry(QtCore.QRect(10, 130, 451, 181))
        self.refs_found.setToolTip("")
        self.refs_found.setStatusTip("")
        self.refs_found.setWhatsThis("")
        self.refs_found.setObjectName("refs_found")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 171, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 320, 171, 16))
        self.label_4.setObjectName("label_4")
        self.refs_error = QtWidgets.QTextBrowser(self.centralwidget)
        self.refs_error.setGeometry(QtCore.QRect(10, 340, 451, 181))
        self.refs_error.setToolTip("")
        self.refs_error.setStatusTip("")
        self.refs_error.setWhatsThis("")
        self.refs_error.setObjectName("refs_error")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "Имя документа (файла):"))
        self.label_2.setText(_translate("MainWindow", "Имя обработанного (итогового) документа (файла):"))
        self.label_3.setText(_translate("MainWindow", "Обнаружены ссылки:"))
        self.label_4.setText(_translate("MainWindow", "Ошибки замены:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
